
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.7"

mkdocs:
  configuration: mkdocs.yml

python:
   install:
     - method: pip
       path: .
       extra_requirements:
         - docs
